site_name: My Digital Garden
site_url: https://zeumer.com
theme:
  name: material
  font:
    text: JetBrains Mono
    code: Rubik

  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dank Mode
      primary: green
      accent: blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: green
      accent: blue

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com
    - icon: simple/instagram
      link: https://instagram.com
    - icon: material/linkedin
      link: https://zeumer.com

copyright: Copyright &copy; 2025 Heiko Zeumer