site_name: My Digital Garden
site_description: Mein Digitaler Garten mit Infos zu Themen die mich interessieren.
site_url: https://zeumer.com
theme:
  name: material
  font:
    text: JetBrains Mono
    code: Rubik
  features:
    - navigation.tabs
    - navigation.footer
  logo: assets/logo.png
  favicon: assets/favicon.ico

    
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dank Mode
      primary: green
      accent: blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: green
      accent: blue

plugins:
  - search:
  - blog:
      blog_dir: ./blog
      archive_date_format: MM/yyyy
      archive_url_date_format: MM/yyyy
      post_url_format: "{slug}"

  - tags:
      tags_file: tags.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/heiko-zeumer-76834a10a/

copyright: Copyright &copy; 2025 Heiko Zeumer

nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md